dist: trusty

language: python
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
    env: BUILD=PYPI
  - os: linux
    python: 3.8
    dist: xenial
    sudo: true

install:
- pip install -r requirements/dev.txt
- pip install -r requirements/test.txt
- pip install pytest-cov

script:
- flake8
- python setup.py test

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: PdeqFOyMytivocWKkX4y2+KvQDvpsGZ0BLYF1WGqEAQu4BCC1ZPsXsfDxR1PtWIo/hccAoEW/Ngm1aaO3HPVMsNfSDh/3M8BXNiBWiMqB0mWoViDQkCnSc5+hm9lrAqo0UTsGcaPqRikygGh3604bM/Fwlrh6X3fx+Z3m0/EE4idu/5i/vy9KwrSqDc+d2PWpiyggxIAeZ7W0yXk8XxQlFKFKMPLzECIu5vqEqFDl8moVDRb3gbSeak5XjxCA0mb0G0AWtdrYoGdj/kgS8UYTU8e0m0U4gwH1HSa71z2PV0x+2eU9y8xbTjtBWXcTikQmQb51H9ZiQ9czGQMgRmVfshpT5m/jZiC9SiM2yykwTB3DFKPAj8tHjO5ss9FOG58nn6RowJ7PpkJm9k46WsEACjob41wmFFiM5BwNxSRALlbUrIzKhKA/gwbupsOUVucjiljjfA5+Hp7XVUIH16En0cVOTq36PPG3XEzXQFB1pmb1YgfM6lhXlw13oMcwO7T/azM/tewsMBif/p4Otj7kVLiYhIKaaX6JsKbdq3LiozZde86ndwq/H+wqj+q9i8X7MfGfXJcU5AWJ+MYG0IdaTXOWsRieMyPdkaw6YFDcwEo4lmHNoKAtiygmExtEzJGUuJjFzCsMNwwVdCpxBnC2iXJdXqVYIXHKFCHKqJYcVg=

deploy:
  skip_cleanup: true
  provider: pypi
  user: apslite
  password:
    secure: ohYDcQyFlpCs0P3YowA+GPkv2Qw7EZBunlsElFUWBESCI+QcQlHeh6+YgR+cbotZTVuLgFTSvVBrk8IpZRjmoiCgqiDpT79keYfj5xubFYTR1ftGkOW6H7rAgzlkxI5OxLcLjrtUx9jlQuTJYqWF6S0vXyjbzke/E2zJ6ZP1upURSZou/QBBpKrVPsXPJC61WFD94ZmkXs+6FQN0HRwXJlahaSG4Lg7UWg/+olCvuxmqIEbKMoKUPKZYVqjiSkhlUSvi6CEFMSys3nxpdpjLWtF84QeVYhrFFCXkyDwCjayibfLIfU+s5Cn7+H1c9e4z8ivQVdd2ohByMr9BteMI7jsPdITvigbzyap8o5Xs1zmA7qdrAO8otZ6fk6C62buL/Zx487VauuhinT/HsGbPPQwZvpZKZWZxQUtEztH4JVBnqHD4rpDNaZ0g5AT1uGUG+2tlvWGVl705rM2D2ISKRGHAoOSFd0DlvpHL4BEpWwaiHGtjXLo/RJcoAeSuNsnidKi5fKND3r4cTystegI8/TpWM3H129IIc4j5jtBWhfDFRkwzVCTyiWSZQGZIdO4iQ+edLlTYWk8Vk/EdBkk1VXEEIk+HQ/2Ahp21ynqDXQA1DNbaQBfdaqBE6ESHnCwiJhQNDLCC30BGcsHpHZJA17ihlE3fc6OZ6rH9dApD1+Y=
  on:
    tags: true
    all_branches: true
    distributions: sdist
    condition: "$BUILD = PYPI"
