dist: trusty

language: python
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
    env: BUILD=PYPI
  - os: linux
    python: 3.8
    dist: xenial
    sudo: true

install:
- pip install -r requirements/dev.txt
- pip install -r requirements/test.txt
- pip install pytest-cov

script:
- flake8
- python setup.py test
- sonar-scanner

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: VJcQOn8TekNPIEn/vnf4fHGZoHha1hoeIVGGT9sYHfqe6zjofbQqAaGO3HMVR7Oliqxe1GQkiw2g+J5YdnRSvqqt2B6EPRiJXJW2jF0irwZ+zsrs/h5LcnQvp6KcIEjC9XmYh3gtkL7GF4Afola0Co4kic7+G2icExKE9JZCfEPExIgjZ6tkx74i0sIbUpdVNas8ODiPwXYcia0DBBh/1NT6p0X4wduSsWEC98rkxWZEyqtMLgL9hkO8TyihnNxsPCpK+ocyAtVmBG0P52A7iGHOi3JjzxVOQXntXhutdJsFXs+wcnFZfKHZf5lwfSKuY45DBr6s5iXo7mWADau3TJ2WeKasK/Bs20iLu2yJArNVqCAKqyA92YBRltowxYlNt3ewK6NrMyETvK0GVzrnBet0jVBfWPztJYi5HdUQZjfHMOiFE4k2kX1sWWI3uSDMS03vppzwo3T+InaZoj/fJaqsOGXMSlkRyKWa8jeK6556pYKo784WdYthijR2sOxdLck19ZaeplI+t3Pre9mGPlKw1gn/TqCPfQaFstYwede4qk+OzPthfDJh/jSobQgHiGhq9C0vzAn+ftSAEYJupNRt33uX18NSf2nH6N9mBaBF7cuSZrWTKmR1D00f4laIv5w+hI/xVq079BJe9xdK0gtxfZcdGMUowILcA+i2PV4=

deploy:
  skip_cleanup: true
  provider: pypi
  user: apslite
  password:
    secure: ohYDcQyFlpCs0P3YowA+GPkv2Qw7EZBunlsElFUWBESCI+QcQlHeh6+YgR+cbotZTVuLgFTSvVBrk8IpZRjmoiCgqiDpT79keYfj5xubFYTR1ftGkOW6H7rAgzlkxI5OxLcLjrtUx9jlQuTJYqWF6S0vXyjbzke/E2zJ6ZP1upURSZou/QBBpKrVPsXPJC61WFD94ZmkXs+6FQN0HRwXJlahaSG4Lg7UWg/+olCvuxmqIEbKMoKUPKZYVqjiSkhlUSvi6CEFMSys3nxpdpjLWtF84QeVYhrFFCXkyDwCjayibfLIfU+s5Cn7+H1c9e4z8ivQVdd2ohByMr9BteMI7jsPdITvigbzyap8o5Xs1zmA7qdrAO8otZ6fk6C62buL/Zx487VauuhinT/HsGbPPQwZvpZKZWZxQUtEztH4JVBnqHD4rpDNaZ0g5AT1uGUG+2tlvWGVl705rM2D2ISKRGHAoOSFd0DlvpHL4BEpWwaiHGtjXLo/RJcoAeSuNsnidKi5fKND3r4cTystegI8/TpWM3H129IIc4j5jtBWhfDFRkwzVCTyiWSZQGZIdO4iQ+edLlTYWk8Vk/EdBkk1VXEEIk+HQ/2Ahp21ynqDXQA1DNbaQBfdaqBE6ESHnCwiJhQNDLCC30BGcsHpHZJA17ihlE3fc6OZ6rH9dApD1+Y=
  on:
    tags: true
    all_branches: true
    distributions: sdist
    condition: "$BUILD = PYPI"
