dist: trusty
language: python
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
    env: BUILD=PYPI
  - os: linux
    python: 3.8
    dist: xenial
    sudo: true
install:
- pip install -r requirements/dev.txt
- pip install -r requirements/test.txt
- pip install pytest-cov
script:
- flake8
- python setup.py test
- sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: cloudbluesonarcube
    token:
      secure: VJcQOn8TekNPIEn/vnf4fHGZoHha1hoeIVGGT9sYHfqe6zjofbQqAaGO3HMVR7Oliqxe1GQkiw2g+J5YdnRSvqqt2B6EPRiJXJW2jF0irwZ+zsrs/h5LcnQvp6KcIEjC9XmYh3gtkL7GF4Afola0Co4kic7+G2icExKE9JZCfEPExIgjZ6tkx74i0sIbUpdVNas8ODiPwXYcia0DBBh/1NT6p0X4wduSsWEC98rkxWZEyqtMLgL9hkO8TyihnNxsPCpK+ocyAtVmBG0P52A7iGHOi3JjzxVOQXntXhutdJsFXs+wcnFZfKHZf5lwfSKuY45DBr6s5iXo7mWADau3TJ2WeKasK/Bs20iLu2yJArNVqCAKqyA92YBRltowxYlNt3ewK6NrMyETvK0GVzrnBet0jVBfWPztJYi5HdUQZjfHMOiFE4k2kX1sWWI3uSDMS03vppzwo3T+InaZoj/fJaqsOGXMSlkRyKWa8jeK6556pYKo784WdYthijR2sOxdLck19ZaeplI+t3Pre9mGPlKw1gn/TqCPfQaFstYwede4qk+OzPthfDJh/jSobQgHiGhq9C0vzAn+ftSAEYJupNRt33uX18NSf2nH6N9mBaBF7cuSZrWTKmR1D00f4laIv5w+hI/xVq079BJe9xdK0gtxfZcdGMUowILcA+i2PV4=
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: apslite
  password:
    secure: FKev30NLa3A7gdpbl2dCH4gJpZ1eQ5ew8cTEeggZqRoiuSHV8xQmAWbGkADhDiafdc98om9GEAi0T38uJbaEbSBVB76W7OWB+dZw9A8olIAb3XOenvhSmdqoR+xRifN6BzjGDw7ebywq5Unxlf5hQcM9LM70HTjUg2L3d8cDIYgQtZXEzkxRFRpa/ptLMYSNjIm+EK6gcmYRWvjbqh8ajg6F2qN2GIcz02XB9GUtp7eofUT5hPnwIKREZ9dJ3Xc+BQtVg13SshaY6WWhH6Pgu+aNg8Nzm7C8EPqAvkxPyNwk4lyankOnu5k8B1cMDqOhPY88RS4Smn29OfhT7CPiEbvdmcxtRqkQwi1N9CxMJPOYTxVp1+pXlDAx3/9s89uRSnbRY4qzUSNxM9a0M7mTcaqkwFrUhvBVZfM1qPyq3gatRsBa2JMzRhY8mZQrbrXmGyjWB62WsKRJy576GzuAOzsUS4jg205SWIz15TJc+OESgdX99L4aHsIG8ClRY63sAr82e9PSyXsNgnGN85LIxHiGSD/5z299lTXpBxbNkip+4DW5LRAjoFM+vyaihFdVevLqlEu3gCvlMgeZapBykNZk2gpXyxp4f59Eet8NpjB6a6pRt4Kyh4qmoRnZ846mO+4AirwrHl/LkXhBJtF490ZI5nyg98fxW51abORiyd8=
  on:
    tags: true
    all_branches: true
    distributions: sdist
    condition: "$BUILD = PYPI"
    repo: cloudblue/django-rql
