site_name: Django RQL Library
site_url: https://github.com/cloudblue/django-rql
repo_name: cloudblue/django-rql
repo_url: https://github.com/cloudblue/django-rql
edit_uri: ""
copyright: Copyright &copy; 2023 Ingram Micro. All Rights Reserved.
extra:
  generator: false
extra_css:
  - css/custom.css
theme:
  name: "material"
  logo: images/logo_full.png
  favicon: images/favicon.ico
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
markdown_extensions:
  - mkautodoc
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - toc:
      toc_depth: 3
  - admonition
  - tables
plugins:
  - glightbox
  - macros:
      module_name: docs/macros
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
watch:
  - docs
  - dj_rql
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - User guide: user_guide.md
  - The "Power of Select": select.md
  - API Reference: reference.md
